"""Module containing all the constraints"""
EMAIL_DOMAIN = "gmail.com"
LOG_FILE = "logs/app.log"
INPUT_FILE = "data/input/Test Files.xlsx"
OUTPUT_CSV = "data/output/students_emails.csv"
OUTPUT_TSV = "data/output/students_emails.tsv"
MALES_CSV = "data/output/males.csv"
FEMALES_CSV = "data/output/females.csv"
MALES_TSV = "data/output/males.tsv"
FEMALES_TSV = "data/output/females.tsv"